  language: python

  python:
    - "2.7.12"

  install:
    - sudo apt-get update
    - pip install --upgrade pip
    - pip install pandas
    - pip install xlrd

  script:
    - python ./Demo3/RecommandSystem/python_unittest.py