version: '3.3'
services:
  tag_api:
    build: ./Demo3/TagServer
    image: tag_api:1.0
    depends_on:
      - luke_postgres
      - luke_redis
    container_name: tagserver
    networks:
      recommend_system:
  
  recommend_api:
    build: ./Demo3/RecommendSystem
    image: recommend_api:1.0 
    ports:
      - "6010:80"
    container_name: recommendapi
    networks:
      recommend_system:

  luke_redis:
    image: redis:latest
    container_name: lukeredis
    networks:
      recommend_system:
  luke_postgres:
    image: postgres:latest
    container_name: lukepostgres
    environment:
      POSTGRES_PASSWORD: lukechen0419
    networks:
      recommend_system:
networks:
  recommend_system:
    driver: bridge

