version: '3.3'
services:
  tag_api:
    build: ./Demo3
    image: tag_api:1.0
    depends_on:
      - luke_postgres
      - luke_redis
    container_name: tagserver
    networks:
      recommand_system:
  
  recommand_api:
    build: ./Demo3/RecommandSystem
    image: recommand_api:1.0 
    ports:
      - "6010:80"
    container_name: recommandapi
    networks:
      recommand_system:

  luke_redis:
    image: redis:latest
    container_name: lukeredis
    networks:
      recommand_system:
  luke_postgres:
    image: postgres:latest
    container_name: lukepostgres
    environment:
      POSTGRES_PASSWORD: lukechen0419
    networks:
      recommand_system:
networks:
  recommand_system:
    driver: bridge

