version: '3.3'
services:
  tag_api: 
    image: tag_api:1.0
    depends_on:
      - postgres
      - redis
    container_name: tagserver
    networks:
      recommend_system:
  
  recommend_api:
    image: recommend_api:1.0 
    ports:
      - "6010:80"
    container_name: recommend_api
    networks:
      recommend_system:

  redis:
    image: redis:latest
    container_name: redis
    networks:
      recommend_system:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: lukechen0419
    networks:
      recommend_system:
networks:
  recommend_system:
    driver: bridge

